spring:
  zipkin:
    base-url: http://zipkin-dep.config.svc.cluster.local:9411
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:tcp://localhost:1521/gav
        username:
        password:
queue:
    maxEntries: 3
    timeout: 5

